name: Test

on:
  workflow_dispatch:
    inputs:
      version_changed:
        description: "Whether version changed"
        required: true
        type: string
      version:
        description: "Current version"
        required: true
        type: string
      run_id:
        description: "Build run ID"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: ./.github/actions/setup-node

      - name: Run tests
        run: npm test

      - name: Dispatch publish workflow
        run: |
          gh workflow run publish.yaml \
            --field version_changed='${{ inputs.version_changed }}' \
            --field version='${{ inputs.version }}' \
            --field run_id='${{ inputs.run_id }}'
        env:
          GH_TOKEN: ${{ github.token }}

      # - name: Trigger publish workflow
      #   if: inputs.version_changed == 'true'
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       await github.rest.actions.createWorkflowDispatch({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         workflow_id: 'publish.yaml',
      #         ref: context.ref,
      #         inputs: {
      #           version_changed: '${{ inputs.version_changed }}',
      #           version: '${{ inputs.version }}',
      #           run_id: '${{ inputs.run_id }}'
      #         }
      #       });
